CREATE TABLE person
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR        NOT NULL,
    age   INT CHECK (age > 0),
    email VARCHAR UNIQUE NOT NULL
);

INSERT INTO person (name, age, email)
VALUES ('Tom', 18, 'tom@mail.ru'),
       ('Bob', 28, 'bob@mail.ru'),
       ('Bob1', 38, 'bob346@mail.ru'),
       ('Bob2', 45, 'bob34563467@mail.ru');